/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    interventions: Intervention;
    'intervention-subpages': InterventionSubpage;
    guides: Guide;
    'glossary-terms': GlossaryTerm;
    surgeons: Surgeon;
    'surgeon-applications': SurgeonApplication;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    interventions: InterventionsSelect<false> | InterventionsSelect<true>;
    'intervention-subpages': InterventionSubpagesSelect<false> | InterventionSubpagesSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    'glossary-terms': GlossaryTermsSelect<false> | GlossaryTermsSelect<true>;
    surgeons: SurgeonsSelect<false> | SurgeonsSelect<true>;
    'surgeon-applications': SurgeonApplicationsSelect<false> | SurgeonApplicationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fr' | 'en-gb') | ('fr' | 'en-gb')[];
  globals: {};
  globalsSelect: {};
  locale: 'fr' | 'en-gb';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor' | 'medical-reviewer';
  /**
   * Pour un relecteur médical : spécialité et numéro d'inscription (RPPS, GMC…). Affichée sur les fiches relues.
   */
  qualification?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "interventions".
 */
export interface Intervention {
  id: number;
  /**
   * Fixe : utilisé par le formulaire de demande.
   */
  interventionId: 'rhinoplasty' | 'abdominoplasty' | 'breast-augmentation';
  category: 'face' | 'body' | 'breast';
  slug: string;
  title: string;
  summary: string;
  description: {
    text: string;
    id?: string | null;
  }[];
  indications: {
    text: string;
    id?: string | null;
  }[];
  contraindications: {
    text: string;
    id?: string | null;
  }[];
  /**
   * Section obligatoire : au moins trois risques.
   */
  risks: {
    name: string;
    detail: string;
    id?: string | null;
  }[];
  procedure: {
    anaesthesia: string;
    duration: string;
    hospitalStay: string;
  };
  recovery: {
    text: string;
    id?: string | null;
  }[];
  alternatives: {
    text: string;
    id?: string | null;
  }[];
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Seul un relecteur médical peut valider. Toute modification du contenu par un autre compte repasse la fiche en brouillon (non indexée).
   */
  medicalReview: {
    status: 'draft' | 'reviewed';
    reviewer?: string | null;
    qualification?: string | null;
    reviewedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intervention-subpages".
 */
export interface InterventionSubpage {
  id: number;
  interventionId: 'rhinoplasty' | 'abdominoplasty' | 'breast-augmentation';
  kind: 'risks' | 'cost' | 'recovery' | 'decision' | 'alternatives';
  title: string;
  summary: string;
  /**
   * La réponse directe à la question, en deux à quatre phrases.
   */
  answer: string;
  sections: {
    heading: string;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  sources: {
    label: string;
    url?: string | null;
    id?: string | null;
  }[];
  /**
   * Seul un relecteur médical peut valider. Toute modification du contenu par un autre compte repasse la fiche en brouillon (non indexée).
   */
  medicalReview: {
    status: 'draft' | 'reviewed';
    reviewer?: string | null;
    qualification?: string | null;
    reviewedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  /**
   * Fixe : relie les versions de chaque marché (hreflang).
   */
  guideId:
    | 'choosing-a-surgeon'
    | 'surgery-abroad'
    | 'preparing-consultation'
    | 'quote-and-cooling-off'
    | 'warning-signs-after-surgery'
    | 'right-time';
  slug: string;
  title: string;
  summary: string;
  answer: string;
  steps: {
    heading: string;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  warningSigns: {
    text: string;
    id?: string | null;
  }[];
  resources: {
    label: string;
    url?: string | null;
    id?: string | null;
  }[];
  interventions?: ('rhinoplasty' | 'abdominoplasty' | 'breast-augmentation')[] | null;
  /**
   * Seul un relecteur médical peut valider. Toute modification du contenu par un autre compte repasse la fiche en brouillon (non indexée).
   */
  medicalReview: {
    status: 'draft' | 'reviewed';
    reviewer?: string | null;
    qualification?: string | null;
    reviewedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glossary-terms".
 */
export interface GlossaryTerm {
  id: number;
  /**
   * Commun aux marchés (ex. seroma) : relie les versions pour hreflang.
   */
  termId: string;
  slug: string;
  term: string;
  aliases?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  definition: string;
  detail: {
    text: string;
    id?: string | null;
  }[];
  /**
   * Seul un relecteur médical peut valider. Toute modification du contenu par un autre compte repasse la fiche en brouillon (non indexée).
   */
  medicalReview: {
    status: 'draft' | 'reviewed';
    reviewer?: string | null;
    qualification?: string | null;
    reviewedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surgeons".
 */
export interface Surgeon {
  id: number;
  /**
   * Tel qu'inscrit au registre, ex. « Dr Claire Martin ».
   */
  displayName: string;
  lastName: string;
  /**
   * Calculée à partir du nom et de la ville si laissée vide.
   */
  slug: string;
  specialty: 'plastic-surgery' | 'ent' | 'maxillofacial' | 'oculoplastic';
  country: 'FR' | 'GB' | 'DE' | 'NL' | 'BE' | 'CH' | 'ES' | 'IT';
  /**
   * RPPS (France), numéro GMC (Royaume-Uni)…
   */
  registryNumber: string;
  practiceName: string;
  address: string;
  postalCode: string;
  city: string;
  /**
   * Calculé.
   */
  citySlug?: string | null;
  languages: ('fr' | 'en' | 'de' | 'nl' | 'es' | 'it' | 'ar' | 'pt')[];
  interventions: ('rhinoplasty' | 'abdominoplasty' | 'breast-augmentation')[];
  /**
   * Factuelle : parcours, spécialité. Aucune promesse, aucun superlatif.
   */
  bio?: string | null;
  /**
   * Réservée aux administrateurs. « Vérifié » exige tous les contrôles du pays et une assurance valide. Le profil n'est publié que vérifié depuis moins d'un an et assuré.
   */
  verification: {
    guide?: string | null;
    checks?: {
      registryIdentity?: boolean | null;
      specialtyTitle?: boolean | null;
      noSanction?: boolean | null;
      insurance?: boolean | null;
      facility?: boolean | null;
    };
    /**
     * Le profil est retiré automatiquement à cette date.
     */
    insuranceExpiresAt?: string | null;
    status: 'pending' | 'verified' | 'suspended';
    renew?: boolean | null;
    verifiedAt?: string | null;
    verifiedBy?: string | null;
    /**
     * Ex. capture de la fiche RPPS du jour, lien vers le registre. Jamais publiée.
     */
    evidence?: string | null;
  };
  /**
   * Abonnement fixe : il ne change ni le classement ni le nombre de demandes.
   */
  subscriptionActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contrôler chaque candidature au registre du pays avant de créer la fiche et le compte.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surgeon-applications".
 */
export interface SurgeonApplication {
  id: number;
  status: 'new' | 'checking' | 'accepted' | 'rejected';
  /**
   * Résultat des contrôles, motif d'un refus. Jamais transmis au candidat tel quel.
   */
  notes?: string | null;
  guide?: string | null;
  fullName: string;
  email: string;
  phone?: string | null;
  country: 'FR' | 'GB' | 'DE' | 'NL' | 'BE' | 'CH' | 'ES' | 'IT';
  registryNumber: string;
  specialty: 'plastic-surgery' | 'ent' | 'maxillofacial' | 'oculoplastic';
  city: string;
  interventions: ('rhinoplasty' | 'abdominoplasty' | 'breast-augmentation')[];
  languages?: ('fr' | 'en' | 'de' | 'nl' | 'es' | 'it' | 'ar' | 'pt')[] | null;
  locale?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'interventions';
        value: number | Intervention;
      } | null)
    | ({
        relationTo: 'intervention-subpages';
        value: number | InterventionSubpage;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'glossary-terms';
        value: number | GlossaryTerm;
      } | null)
    | ({
        relationTo: 'surgeons';
        value: number | Surgeon;
      } | null)
    | ({
        relationTo: 'surgeon-applications';
        value: number | SurgeonApplication;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  qualification?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "interventions_select".
 */
export interface InterventionsSelect<T extends boolean = true> {
  interventionId?: T;
  category?: T;
  slug?: T;
  title?: T;
  summary?: T;
  description?:
    | T
    | {
        text?: T;
        id?: T;
      };
  indications?:
    | T
    | {
        text?: T;
        id?: T;
      };
  contraindications?:
    | T
    | {
        text?: T;
        id?: T;
      };
  risks?:
    | T
    | {
        name?: T;
        detail?: T;
        id?: T;
      };
  procedure?:
    | T
    | {
        anaesthesia?: T;
        duration?: T;
        hospitalStay?: T;
      };
  recovery?:
    | T
    | {
        text?: T;
        id?: T;
      };
  alternatives?:
    | T
    | {
        text?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  medicalReview?:
    | T
    | {
        status?: T;
        reviewer?: T;
        qualification?: T;
        reviewedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intervention-subpages_select".
 */
export interface InterventionSubpagesSelect<T extends boolean = true> {
  interventionId?: T;
  kind?: T;
  title?: T;
  summary?: T;
  answer?: T;
  sections?:
    | T
    | {
        heading?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  medicalReview?:
    | T
    | {
        status?: T;
        reviewer?: T;
        qualification?: T;
        reviewedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  guideId?: T;
  slug?: T;
  title?: T;
  summary?: T;
  answer?: T;
  steps?:
    | T
    | {
        heading?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  warningSigns?:
    | T
    | {
        text?: T;
        id?: T;
      };
  resources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  interventions?: T;
  medicalReview?:
    | T
    | {
        status?: T;
        reviewer?: T;
        qualification?: T;
        reviewedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glossary-terms_select".
 */
export interface GlossaryTermsSelect<T extends boolean = true> {
  termId?: T;
  slug?: T;
  term?: T;
  aliases?:
    | T
    | {
        text?: T;
        id?: T;
      };
  definition?: T;
  detail?:
    | T
    | {
        text?: T;
        id?: T;
      };
  medicalReview?:
    | T
    | {
        status?: T;
        reviewer?: T;
        qualification?: T;
        reviewedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surgeons_select".
 */
export interface SurgeonsSelect<T extends boolean = true> {
  displayName?: T;
  lastName?: T;
  slug?: T;
  specialty?: T;
  country?: T;
  registryNumber?: T;
  practiceName?: T;
  address?: T;
  postalCode?: T;
  city?: T;
  citySlug?: T;
  languages?: T;
  interventions?: T;
  bio?: T;
  verification?:
    | T
    | {
        guide?: T;
        checks?:
          | T
          | {
              registryIdentity?: T;
              specialtyTitle?: T;
              noSanction?: T;
              insurance?: T;
              facility?: T;
            };
        insuranceExpiresAt?: T;
        status?: T;
        renew?: T;
        verifiedAt?: T;
        verifiedBy?: T;
        evidence?: T;
      };
  subscriptionActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surgeon-applications_select".
 */
export interface SurgeonApplicationsSelect<T extends boolean = true> {
  status?: T;
  notes?: T;
  guide?: T;
  fullName?: T;
  email?: T;
  phone?: T;
  country?: T;
  registryNumber?: T;
  specialty?: T;
  city?: T;
  interventions?: T;
  languages?: T;
  locale?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}